# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on:
  release:
    types:
    - published
name: publish
jobs:
  publish:
    name: publish to npmjs.com
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v3

    - name: Build
      uses: ./.github/actions/build
      with:
        registry-url: https://registry.npmjs.org/

    - name: Publish package
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
