# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on: push
name: Linux
jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v3

    - name: Build
      uses: ./.github/actions/build

    - name: Verify
      run: npm run verify
