# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on: push
name: Windows
jobs:
  verify:
    name: Verify
    runs-on: windows-latest
    strategy:
      matrix:
        nodejs:
        - 8
        - 10
        - 12
      fail-fast: false
    steps:
    - name: Turn off auto-crlf
      run: git config --global core.autocrlf false
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Output versions
      run: |
        node -v
        npm -v
    - name: Install dependencies
      run: |
        npm ci
        if (!$?) {
          npm i
        }
    - name: Verify
      run: npm run verify
