# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on: push
name: Syntax check
jobs:
  syntax:
    name: Syntax check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-latest
        - macos-latest
        - ubuntu-latest
        nodejs:
        - "6.9.0" # minimum version Babel works: https://github.com/babel/babel/blob/master/packages/babel-core/package.json
        - "8.0.0"
        - "10.0.0"
        - "12.0.0"
      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Output versions
      run: |
        node -v
        npm -v
    - name: Install dependencies
      run: npm i
    - name: Build
      run: npm run build
    - name: Install dependencies (only production)
      run: npm i --only=production
    - name: Check syntax
      run: node ./dist/index.js
